schema_path: config/dataset_schema.yaml
dataset:
  altitude:
    provider: srtm         # srtm|ign|demo|none
    api_url: http://localhost:5004/enrich_terrain
    fill_strategy: forward
  events:
    categories: [infra, behavior, context]
  delivery:
    buttons: { enabled: true }
inertial:
  gyro: { noise_std: 0.02, drift_per_sec: 0.0005, seed: 42 }
simulation: { hz: 10, target_speed_kmh: 30 }

injection:
  acceleration:
    amplitude: 5.0
    duration_s: 0.8
    min_speed_kmh: 30
  freinage:
    amplitude: -6.0
    duration_s: 0.8
    min_speed_kmh: 30
  dos_dane:
    total_points: 20
    amplitude_peak_positive: 7.6
    amplitude_peak_negative: -7.6
  trottoir:
    total_points: 13
    acc_y_mean: 1.75
    acc_z_mean: 8.0
  nid_de_poule:
    pattern_acc_z: [4.2, 3.5, -5.3, 6.1, 9.8, 9.8]

injection_indices: [100, 42265, 84431, 126597, 168763]

general:
  force_speed_before_injection: 30
  inertial_noise: true
  detection_thresholds:
    acc_y_virage: 0.15
    heading_virage: 15
    validate_turns_threshold: 0.15

kinematics:
  heading_smooth_window: 41
